# Generated by Django 4.2.4 on 2023-08-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
