# Generated by Django 4.2.4 on 2023-08-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_order',
            new_name='date_orderd',
        ),
    ]
