# Generated by Django 4.2.4 on 2023-08-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Order',
            new_name='order',
        ),
    ]
