# Generated by Django 4.2.4 on 2023-08-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_order_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_ref',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='order_ref',
        ),
    ]
