# Generated by Django 4.2.4 on 2023-08-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
