# Generated by Django 4.2.4 on 2023-08-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_promotion_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='title',
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='No Name', max_length=200),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', to='store.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
